travis:
  secure:
    BINSTAR_TOKEN: b6UQGtme/scaoG0JCrDT20RbhFGbsgFQi68an+nwNMKflj4m0pxQB6vRMTFs4SdqN2Qo5Ud6B22Hs9ZjS/sALkNdv4QnZ/xXw6MgNE5ffYxz/X5IvVNN2K9XLnmpJDJsbIEA/9WQv+q5Az7N9giLV5ODcEjJ1szWi3H45Hxo7BfMRaNWx7bQR8JJ6Ei8JguAdgdgvrO+1akRlZfDGMSr8L/0/qqpBJBQcxlTFUV01GL3vGZJi/kPkLnwOXgL5aKJtILku+gXEFeGKGWykZeLMUBgWe1CQuREJjM/iYopyXozorlRVjfRMwcG1vc1qhnkCN+Eag8QOy7AyR/QZjt+HgCk+4Z+8AdrmpgKK2c35aHf23Ni7Y5clNAaVaZijtIeS0Vvrx0nw0FSjw2bvaUydazu/NwWY3cSFwqX8+RRBbLnj9iXKkt5FzctW5aIrj0gPmF2uoD8+eOQ8ut48EmaQQs5tPG0sLYg9MDexXu2W5YhKSzXt0kBVgGzLZWRkXzYgN7MiTHgcRr7sYoB6rOipShuL9Ao4ppu3ttDIy7Vunjxa8qNgMUbaWJQizftjm/LJ+bmCZGiLH5JpmTOl/s8qsmJ7T4/r5rxbyM14qKklqVZuFJGmfLy772Gkxi9PtyrsmyxPVn3cz8g6pwGVJ/+woNFQtjzIoxIn2CHAhEuf7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
